version: '3.3'

services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app

    ports:
      - 5435:5432

    volumes:
      - app-db-volume:/var/lib/postgresql/data/
      - ./init_db:/init_db

volumes:
  app-db-volume: