version: '3.3'

services:
  db:
    image: postgres:13.7
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: mvc

    ports:
      - '5435:5432'

    volumes:
      - app-volume:/var/lib/postgresql/data
      - ./init_db:/init_db

volumes:
  app-volume: